-- Curatable global disaster-relief directory (powers /red-ayuda and /api/aid-orgs).
-- Operators edit entries from the admin console; the public page reads this table
-- and falls back to its baked-in snapshot when offline.
CREATE TABLE IF NOT EXISTS aid_orgs (
  id          TEXT PRIMARY KEY,
  region      TEXT NOT NULL,        -- Spanish region label (chart grouping)
  scope       TEXT,                 -- country / scope
  name        TEXT NOT NULL,
  type        TEXT,
  web         TEXT,
  phone       TEXT,
  email       TEXT,
  focus       TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  updated_ms  INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_aid_orgs_region ON aid_orgs(region);

INSERT OR IGNORE INTO aid_orgs
  (id, region, scope, name, type, web, phone, email, focus, sort_order, updated_ms)
VALUES
('aid_0001','Respondedores Globales','Global','IFRC – Int''l Federation of Red Cross & Red Crescent','Int''l NGO (Red Cross movement)','https://www.ifrc.org','+41 22 730 4222','secretariat@ifrc.org','World''s largest humanitarian network; 191 national societies, rapid disaster response',1,0),
('aid_0002','Respondedores Globales','Global','ICRC – Int''l Committee of the Red Cross','Int''l NGO (Red Cross movement)','https://www.icrc.org','+41 22 734 6001','press@icrc.org','Conflict-zone aid, missing persons, emergency relief',2,0),
('aid_0003','Respondedores Globales','Global','Médecins Sans Frontières / Doctors Without Borders','Int''l medical NGO','https://www.msf.org','+41 22 849 8400','verify on site','Emergency medical care in disasters, epidemics & conflict',3,0),
('aid_0004','Respondedores Globales','Global','International Rescue Committee (IRC)','Int''l NGO','https://www.rescue.org','+1 212 551 3000','verify on site','Crisis response, resettlement, health & recovery',4,0),
('aid_0005','Respondedores Globales','Global','Mercy Corps','Int''l NGO','https://www.mercycorps.org','+1 503 896 5000 / 1-888-842-0842','verify on site','Rapid disaster response, water, food, economic recovery',5,0),
('aid_0006','Respondedores Globales','Global','Save the Children International','Int''l NGO','https://www.savethechildren.net','+44 20 3272 0300','verify on site','Child-focused emergency relief & protection',6,0),
('aid_0007','Respondedores Globales','Global','CARE International','Int''l NGO','https://www.care-international.org','+1 404 681 2552','verify on site','Emergency food, water, shelter; poverty & gender focus',7,0),
('aid_0008','Respondedores Globales','Global','Oxfam International','Int''l NGO','https://www.oxfam.org','+254 20 2820000 (Nairobi)','verify on site','Water/sanitation & emergency relief in disasters',8,0),
('aid_0009','Respondedores Globales','Global','World Vision International','Int''l NGO','https://www.wvi.org','verify on site','verify on site','Child-focused relief & development, rapid response',9,0),
('aid_0010','Respondedores Globales','USA','Direct Relief','Medical-supply NGO','https://www.directrelief.org','+1 805 964 4767','info@directrelief.org','Donated medicines & supplies to disaster zones worldwide',10,0),
('aid_0011','Respondedores Globales','USA','Americares','Medical-relief NGO','https://www.americares.org','+1 203 658 9500 / 1-800-486-4357','verify on site','Emergency medicine, health programs in disasters',11,0),
('aid_0012','Respondedores Globales','UK','ShelterBox','Shelter NGO','https://www.shelterbox.org','+44 1872 302600','verify on site','Emergency shelter & tools to families after disasters',12,0),
('aid_0013','Respondedores Globales','USA','Team Rubicon','Veteran-led response NGO','https://www.teamrubiconusa.org','+1 310 640 8787','verify on site','Veteran-led disaster response & rebuild teams',13,0),
('aid_0014','Respondedores Globales','USA','All Hands and Hearts','Volunteer rebuild NGO','https://www.allhandsandhearts.org','+1 508 905 3777','verify on site','Volunteer-powered disaster rebuild (schools, homes)',14,0),
('aid_0015','Respondedores Globales','Canada','GlobalMedic','Rapid-response NGO','https://www.globalmedic.ca','+1 416 661 1499','verify on site','Water purification, medical & search-rescue rapid teams',15,0),
('aid_0016','Respondedores Globales','USA','Samaritan''s Purse','Faith-based relief NGO','https://www.samaritanspurse.org','+1 828 262 1980','verify on site','Emergency field hospitals, shelter & relief',16,0),
('aid_0017','Respondedores Globales','USA','International Medical Corps','Medical-relief NGO','https://internationalmedicalcorps.org','+1 310 826 7800','verify on site','Emergency medical teams & health-system recovery',17,0),
('aid_0018','Respondedores Globales','USA','Project HOPE','Global-health NGO','https://www.projecthope.org','+1 844 349 0188','verify on site','Health-worker deployment & medical relief in disasters',18,0),
('aid_0019','Respondedores Globales','USA','Catholic Relief Services (CRS)','Faith-based relief NGO','https://www.crs.org','1-800-235-2772','verify on site','Emergency response & recovery in 100+ countries',19,0),
('aid_0020','Respondedores Globales','UK','Islamic Relief Worldwide','Faith-based relief NGO','https://www.islamic-relief.org','+44 121 605 5555','verify on site','Emergency aid & rebuild, esp. Muslim-majority regions',20,0),
('aid_0021','Respondedores Globales','USA','Habitat for Humanity Int''l','Shelter NGO','https://www.habitat.org','1-800-422-4828','verify on site','Disaster shelter response & rebuild',21,0),
('aid_0022','Respondedores Globales','USA','Convoy of Hope','Relief NGO','https://www.convoyofhope.org','+1 417 823 8998','verify on site','Disaster feeding & supply distribution',22,0),
('aid_0023','ONU / Intergubernamental','Global','UN OCHA (Office for Coordination of Humanitarian Affairs)','UN Secretariat','https://www.unocha.org','NY +1 212 963 1234 / Geneva +41 22 917 1234','verify on site','Coordinates all UN humanitarian disaster response',23,0),
('aid_0024','ONU / Intergubernamental','Global','UNDAC (UN Disaster Assessment & Coordination)','OCHA rapid-response mechanism','https://undac.un.org','+41 22 917 1600 (OCHA 24/7 duty)','undac@un.org','Deployable expert teams for sudden-onset disaster assessment',24,0),
('aid_0025','ONU / Intergubernamental','Global','INSARAG (Int''l Search & Rescue Advisory Group)','Intergovernmental network (OCHA-hosted)','https://insarag.org','+41 22 917 1600 (OCHA duty, emergencies)','insarag@un.org','Global USAR standards & team classification',25,0),
('aid_0026','ONU / Intergubernamental','Global','GDACS (Global Disaster Alert & Coordination System)','UN + EC alert system','https://www.gdacs.org','N/A (automated)','web form (email cancelled)','24/7 automated disaster alerts + Virtual OSOCC',26,0),
('aid_0027','ONU / Intergubernamental','Italy','UN World Food Programme (WFP)','UN agency','https://www.wfp.org','+39 06 65131','info@wfp.org','Emergency food assistance & logistics backbone',27,0),
('aid_0028','ONU / Intergubernamental','USA','UNICEF – Emergency Programmes (EMOPS)','UN fund','https://www.unicef.org','+1 212 326 7000','verify on site','Children''s emergency WASH, nutrition, health, protection',28,0),
('aid_0029','ONU / Intergubernamental','Switzerland','WHO Health Emergencies Programme','UN agency','https://www.who.int/emergencies','+41 22 791 2111','info@who.int','Health-emergency detection, prep & response',29,0),
('aid_0030','ONU / Intergubernamental','Switzerland','UNDRR (UN Office for Disaster Risk Reduction)','UN office','https://www.undrr.org','web form','web form','Sendai Framework; global disaster-risk policy',30,0),
('aid_0031','ONU / Intergubernamental','Switzerland','IOM (Int''l Organization for Migration)','UN-related agency','https://www.iom.int','+41 22 717 9111','verify on site','Displacement & humanitarian response',31,0),
('aid_0032','ONU / Intergubernamental','Switzerland','UNHCR (UN Refugee Agency)','UN agency','https://www.unhcr.org','+41 22 739 8111 (routes to duty officer)','verify on site','Refugee & displaced-person emergency response',32,0),
('aid_0033','ONU / Intergubernamental','Belgium (EU)','EU ERCC / DG ECHO (Emergency Response Coordination Centre)','EU body','https://erccportal.jrc.ec.europa.eu','24/7 ops centre (line not public)','web form','EU 24/7 civil-protection & humanitarian coordination hub',33,0),
('aid_0034','ONU / Intergubernamental','USA','World Bank GFDRR (Global Facility for Disaster Reduction & Recovery)','Multi-donor facility','https://www.gfdrr.org','+1 202 473 6253','web form','Disaster prevention, prep & recovery financing',34,0),
('aid_0035','Sismos y Rescate (USAR)','USA','USGS Earthquake Hazards Program (NEIC, ShakeMap, PAGER)','Govt science agency','https://earthquake.usgs.gov','1-888-275-8747 (ASK-USGS)','verify on site','Global quake monitoring, alerts, impact estimates',35,0),
('aid_0036','Sismos y Rescate (USAR)','USA','USAID BHA (Bureau for Humanitarian Assistance)','Govt agency','https://www.usaid.gov/humanitarian-assistance','verify on site','verify on site','US lead for int''l disaster response & USAR deployment',36,0),
('aid_0037','Sismos y Rescate (USAR)','USA','Fairfax County Urban SAR (VA-TF1)','USAR task force','https://www.fairfaxcounty.gov/fire-ems/urban-search-and-rescue','verify on site','verify on site','INSARAG-heavy US int''l search & rescue team',37,0),
('aid_0038','Sismos y Rescate (USAR)','USA','Los Angeles County USAR (CA-TF2)','USAR task force','https://fire.lacounty.gov','verify on site','verify on site','INSARAG-heavy US int''l search & rescue team',38,0),
('aid_0039','Sismos y Rescate (USAR)','France','EMSC (European-Mediterranean Seismological Centre)','Seismic network','https://www.emsc-csem.org','verify on site','verify on site','Real-time Euro-Med earthquake info & felt reports',39,0),
('aid_0040','Sismos y Rescate (USAR)','Germany','GFZ Helmholtz Centre for Geosciences','Research institute','https://www.gfz.de','+49 331 6264 0','verify on site','Global seismology, GEOFON network',40,0),
('aid_0041','Sismos y Rescate (USAR)','UK','ISC (International Seismological Centre)','Research body','https://www.isc.ac.uk','+44 1635 861022','verify on site','Definitive global earthquake bulletin',41,0),
('aid_0042','Sismos y Rescate (USAR)','Italy','GEM Foundation (Global Earthquake Model)','Nonprofit foundation','https://www.globalquakemodel.org','+39 0382 5169865','info@globalquakemodel.org','Open seismic-hazard & risk modeling worldwide',42,0),
('aid_0043','Sismos y Rescate (USAR)','Germany','@fire – Internationaler Katastrophenschutz','NGO USAR','https://www.at-fire.de','+49 800 7777 111 (24/7)','info@at-fire.de','Rapid int''l USAR, wildfire & medical aid',43,0),
('aid_0044','Sismos y Rescate (USAR)','Germany','I.S.A.R. Germany','NGO heavy USAR (INSARAG)','https://isar-germany.de','+49 203 9863 00-0','info@isar-germany.de','Int''l urban search & rescue + medical relief',44,0),
('aid_0045','Sismos y Rescate (USAR)','UK','UK-ISAR (UK Int''l Search & Rescue)','Govt USAR consortium','https://www.ukisar.org','via FCDO 24/7 (not public)','verify on site','UK gov int''l USAR team for sudden-onset disasters',45,0),
('aid_0046','Sismos y Rescate (USAR)','Japan','JICA – Japan Disaster Relief (JDR)','Govt agency','https://www.jica.go.jp/english/activities/schemes/jdr/','+81 3 5226 6660','web form','Japan''s SAR, medical & expert teams abroad',46,0),
('aid_0047','Sismos y Rescate (USAR)','China','China Earthquake Administration (CEA)','Govt agency','https://www.cea.gov.cn','+86 10 88015375','verify on site','National quake monitoring, forecasting & response',47,0),
('aid_0048','Sismos y Rescate (USAR)','China','China Int''l Search & Rescue Team (CISAR)','Heavy USAR (INSARAG)','https://www.cea.gov.cn','verify on site','verify on site','Heavy USAR for quakes, domestic & abroad',48,0),
('aid_0049','Sismos y Rescate (USAR)','Syria','Syria Civil Defence (White Helmets)','Volunteer rescue NGO','https://www.whitehelmets.org','verify on site','verify on site','Search & rescue in NW Syria (war + 2023 quake)',49,0),
('aid_0050','Américas','USA','FEMA (Federal Emergency Management Agency)','Nat''l disaster agency','https://www.fema.gov','1-800-621-3362','verify on site','Federal disaster response, recovery, mitigation',50,0),
('aid_0051','Américas','Canada','Public Safety Canada – Government Operations Centre','Nat''l coordination','https://www.publicsafety.gc.ca','verify on site','verify on site','Federal all-hazard emergency coordination',51,0),
('aid_0052','Américas','Mexico','Coordinación Nacional de Protección Civil (CNPC) / CENAPRED','Nat''l disaster agency','https://www.gob.mx/cnpc','verify on site','verify on site','Civil protection; CENAPRED = seismic/disaster research',52,0),
('aid_0053','Américas','Guatemala','CONRED','Nat''l disaster agency','https://conred.gob.gt','1566 (hotline)','verify on site','Disaster reduction & emergency coordination',53,0),
('aid_0054','Américas','Belize','NEMO (Nat''l Emergency Management Org)','Nat''l disaster agency','https://nemo.org.bz','verify on site','verify on site','National disaster prep & response',54,0),
('aid_0055','Américas','Honduras','COPECO','Nat''l disaster agency','https://copeco.gob.hn','verify on site','verify on site','Risk management & emergency contingencies',55,0),
('aid_0056','Américas','El Salvador','Dirección General de Protección Civil','Nat''l disaster agency','https://proteccioncivil.gob.sv','verify on site','verify on site','Civil protection, prevention & mitigation',56,0),
('aid_0057','Américas','Nicaragua','SINAPRED','Nat''l disaster agency','https://www.sinapred.gob.ni','verify on site','verify on site','National disaster prevention & response system',57,0),
('aid_0058','Américas','Costa Rica','CNE (Comisión Nacional de Emergencias)','Nat''l disaster agency','https://www.cne.go.cr','verify on site','verify on site','Risk prevention & emergency response',58,0),
('aid_0059','Américas','Panama','SINAPROC','Nat''l disaster agency','https://www.sinaproc.gob.pa','verify on site','verify on site','Civil protection & emergency management',59,0),
('aid_0060','Américas','Central America','CEPREDENAC (regional, SICA)','Regional body','https://www.cepredenac.org','verify on site','verify on site','Central America disaster-prevention coordination',60,0),
('aid_0061','Américas','Colombia','UNGRD','Nat''l disaster agency','https://www.gestiondelriesgo.gov.co','verify on site','verify on site','National disaster-risk management',61,0),
('aid_0062','Américas','Venezuela','Protección Civil (PC)','Nat''l disaster agency','https://www.pcivil.gob.ve','verify on site','verify on site','Lead civil-protection / disaster-response body',62,0),
('aid_0063','Américas','Venezuela','FUNVISIS','Seismic research institute','http://www.funvisis.gob.ve','verify on site','verify on site','Seismic monitoring & research (research only)',63,0),
('aid_0064','Américas','Ecuador','SNGRE','Nat''l disaster agency','https://www.gestionderiesgos.gob.ec','verify on site','verify on site','Leads national risk-management system',64,0),
('aid_0065','Américas','Peru','INDECI','Nat''l disaster agency','https://www.gob.pe/indeci','verify on site','verify on site','Civil defense within SINAGERD',65,0),
('aid_0066','Américas','Bolivia','VIDECI (Viceministerio de Defensa Civil)','Nat''l disaster agency','https://www.defensacivil.gob.bo','verify on site','verify on site','Civil defense & emergency response',66,0),
('aid_0067','Américas','Chile','SENAPRED (ex-ONEMI)','Nat''l disaster agency','https://www.senapred.cl','verify on site','verify on site','Disaster prevention & response (high seismic)',67,0),
('aid_0068','Américas','Argentina','SINAGIR','Nat''l disaster agency','https://www.argentina.gob.ar/sinagir','verify on site','verify on site','Integral risk management & civil protection',68,0),
('aid_0069','Américas','Brazil','SEDEC / CENAD','Nat''l disaster agency','https://www.gov.br/mdr','CENAD (61) 2034-4601','cenad@mdr.gov.br','Nat''l civil defense; CENAD = 24/7 disaster center',69,0),
('aid_0070','Américas','Paraguay','SEN (Secretaría de Emergencia Nacional)','Nat''l disaster agency','https://www.sen.gov.py','verify on site','verify on site','National emergency management',70,0),
('aid_0071','Américas','Uruguay','SINAE','Nat''l disaster agency','https://www.gub.uy/sistema-nacional-emergencias','verify on site','verify on site','National emergency coordination',71,0),
('aid_0072','Américas','Guyana','Civil Defence Commission (CDC)','Nat''l disaster agency','https://cdc.gy','verify on site','verify on site','National disaster prep & response',72,0),
('aid_0073','Américas','Suriname','NCCR','Nat''l disaster agency','verify (via gov.sr)','verify on site','verify on site','National disaster-management coordination',73,0),
('aid_0074','Américas','Cuba','Defensa Civil de Cuba','Nat''l disaster agency','verify (via gob.cu)','verify on site','verify on site','Military-led civil defense (hurricane focus)',74,0),
('aid_0075','Américas','Haiti','DGPC (Direction Générale de la Protection Civile)','Nat''l disaster agency','https://protectioncivile.gouv.ht','verify on site','verify on site','National civil protection (high quake risk)',75,0),
('aid_0076','Américas','Dominican Republic','COE (Centro de Operaciones de Emergencias)','Nat''l disaster agency','https://www.coe.gob.do','verify on site','verify on site','Emergency operations coordination',76,0),
('aid_0077','Américas','Jamaica','ODPEM','Nat''l disaster agency','https://www.odpem.org.jm','verify on site','verify on site','Disaster preparedness & emergency management',77,0),
('aid_0078','Américas','Trinidad & Tobago','ODPM','Nat''l disaster agency','https://www.odpm.gov.tt','verify on site','verify on site','National disaster prep & management',78,0),
('aid_0079','Américas','Bahamas','NEMA','Nat''l disaster agency','https://www.nema.gov.bs','verify on site','verify on site','National emergency / hurricane management',79,0),
('aid_0080','Américas','Barbados','Department of Emergency Management (DEM)','Nat''l disaster agency','https://www.dem.gov.bb','verify on site','verify on site','National disaster management',80,0),
('aid_0081','Américas','Caribbean','CDEMA (regional, CARICOM)','Regional body','https://www.cdema.org','verify on site','verify on site','Caribbean regional disaster coordination',81,0),
('aid_0082','Europa y Asia Central','United Kingdom','Cabinet Office – Resilience Directorate','Nat''l coordination','https://www.gov.uk/government/organisations/cabinet-office','999 / 112','verify on site','Central govt emergency planning & resilience',82,0),
('aid_0083','Europa y Asia Central','Ireland','Office of Emergency Planning','Nat''l coordination','https://www.gov.ie/en/organisation/office-of-emergency-planning/','999 / 112','verify on site','National major-emergency coordination',83,0),
('aid_0084','Europa y Asia Central','France','DGSCGC (Sécurité Civile)','Nat''l disaster agency','https://www.interieur.gouv.fr/securite-civile','112 / 18','verify on site','Civil security, firefighting & crisis mgmt',84,0),
('aid_0085','Europa y Asia Central','Germany','BBK (Federal Office of Civil Protection)','Nat''l disaster agency','https://www.bbk.bund.de','verify on site','verify on site','Federal civil protection & disaster assistance',85,0),
('aid_0086','Europa y Asia Central','Germany','THW (Federal Agency for Technical Relief)','Operational relief','https://www.thw.de','verify on site','verify on site','Operational technical/engineering disaster relief',86,0),
('aid_0087','Europa y Asia Central','Italy','Dipartimento della Protezione Civile','Nat''l disaster agency','https://www.protezionecivile.gov.it','800 840 840 / 112','verify on site','National civil protection coordination',87,0),
('aid_0088','Europa y Asia Central','Italy','INGV','Seismic institute','https://www.ingv.it','verify on site','verify on site','Seismic/volcanic monitoring (feeds Prot. Civile)',88,0),
('aid_0089','Europa y Asia Central','Spain','DGPCE (Protección Civil)','Nat''l disaster agency','https://www.proteccioncivil.es','112','verify on site','National civil protection',89,0),
('aid_0090','Europa y Asia Central','Portugal','ANEPC','Nat''l disaster agency','https://www.prociv.gov.pt','112','verify on site','National emergency & civil protection',90,0),
('aid_0091','Europa y Asia Central','Netherlands','NCTV / Veiligheidsregio''s','Nat''l coordination','https://www.nctv.nl','112','verify on site','National crisis coordination; 25 safety regions',91,0),
('aid_0092','Europa y Asia Central','Belgium','NCCN (National Crisis Centre)','Nat''l coordination','https://crisiscentrum.be','112','verify on site','National crisis centre',92,0),
('aid_0093','Europa y Asia Central','Luxembourg','CGDIS','Nat''l rescue service','https://www.cgdis.lu','112','verify on site','National rescue, fire & civil protection',93,0),
('aid_0094','Europa y Asia Central','Switzerland','BABS (Federal Office for Civil Protection)','Nat''l disaster agency','https://www.babs.admin.ch','112','verify on site','Federal civil protection coordination',94,0),
('aid_0095','Europa y Asia Central','Austria','BMI – SKKM','Nat''l coordination','https://www.bmi.gv.at','112','verify on site','State crisis & disaster-protection management',95,0),
('aid_0096','Europa y Asia Central','Denmark','DEMA (Beredskabsstyrelsen)','Nat''l disaster agency','https://www.brs.dk','112','verify on site','National emergency mgmt & rescue',96,0),
('aid_0097','Europa y Asia Central','Norway','DSB','Nat''l disaster agency','https://www.dsb.no','110 / 112','verify on site','National civil protection & emergency planning',97,0),
('aid_0098','Europa y Asia Central','Sweden','MSB (Civil Contingencies Agency)','Nat''l disaster agency','https://www.msb.se','112','verify on site','Civil protection, contingency & rescue',98,0),
('aid_0099','Europa y Asia Central','Finland','Min. Interior – Rescue Services Dept','Nat''l disaster agency','https://intermin.fi/en/rescue-services','112','verify on site','National rescue services & civil preparedness',99,0),
('aid_0100','Europa y Asia Central','Iceland','Almannavarnir (Civil Protection)','Nat''l disaster agency','https://www.almannavarnir.is','112','verify on site','National civil protection (volcanic/seismic)',100,0),
('aid_0101','Europa y Asia Central','Poland','RCB / State Fire Service (PSP)','Nat''l disaster agency','https://www.gov.pl/web/rcb','112','verify on site','Govt security centre + State Fire Service',101,0),
('aid_0102','Europa y Asia Central','Czechia','Fire Rescue Service (HZS ČR)','Nat''l disaster agency','https://www.hzscr.cz','112 / 150','verify on site','Fire & rescue / integrated rescue system',102,0),
('aid_0103','Europa y Asia Central','Slovakia','Min. Interior – Crisis Mgmt Section','Nat''l disaster agency','https://www.minv.sk','112 / 150','verify on site','Crisis management & civil protection',103,0),
('aid_0104','Europa y Asia Central','Hungary','BM OKF (Nat''l Disaster Mgmt)','Nat''l disaster agency','https://www.katasztrofavedelem.hu','112','verify on site','National disaster management directorate',104,0),
('aid_0105','Europa y Asia Central','Romania','IGSU','Nat''l disaster agency','https://www.igsu.ro','112','verify on site','General Inspectorate for Emergency Situations',105,0),
('aid_0106','Europa y Asia Central','Bulgaria','GDPBZN (Fire Safety & Civil Protection)','Nat''l disaster agency','https://www.mvr.bg/gdpbzn','112','verify on site','Fire safety & civil protection directorate',106,0),
('aid_0107','Europa y Asia Central','Greece','General Secretariat for Civil Protection','Nat''l disaster agency','https://www.civilprotection.gov.gr','112','verify on site','National civil protection coordination',107,0),
('aid_0108','Europa y Asia Central','Greece','OASP / EPPO','Earthquake-planning org','https://www.oasp.gr','verify on site','verify on site','Earthquake planning & protection specialist',108,0),
('aid_0109','Europa y Asia Central','Croatia','Civil Protection Directorate (MUP)','Nat''l disaster agency','https://civilna-zastita.gov.hr','112','verify on site','National civil protection directorate',109,0),
('aid_0110','Europa y Asia Central','Slovenia','URSZR','Nat''l disaster agency','https://www.gov.si/drzavni-organi/organi-v-sestavi/uprava-za-zascito-in-resevanje/','112','verify on site','Civil protection & disaster relief',110,0),
('aid_0111','Europa y Asia Central','Serbia','Sector for Emergency Management (MUP)','Nat''l disaster agency','https://www.mup.gov.rs/sektor-za-vanredne-situacije','112 / 193','verify on site','Emergency management sector',111,0),
('aid_0112','Europa y Asia Central','Bosnia & Herzegovina','Min. Security – Protection & Rescue','Nat''l disaster agency','https://www.msb.gov.ba','112 / 121','verify on site','Civil protection (state + entity level)',112,0),
('aid_0113','Europa y Asia Central','North Macedonia','Protection & Rescue Directorate (DZS)','Nat''l disaster agency','https://dzs.gov.mk','112','verify on site','National protection & rescue directorate',113,0),
('aid_0114','Europa y Asia Central','Albania','AKMC (Nat''l Civil Protection Agency)','Nat''l disaster agency','https://mab.gov.al','112 / 129','verify on site','National civil protection agency',114,0),
('aid_0115','Europa y Asia Central','Montenegro','Directorate for Protection & Rescue (MUP)','Nat''l disaster agency','https://www.gov.me/mup','112','verify on site','Protection & rescue directorate',115,0),
('aid_0116','Europa y Asia Central','Kosovo','Emergency Management Agency (AME/EMA)','Nat''l disaster agency','https://ame.rks-gov.net','112','verify on site','National emergency management agency',116,0),
('aid_0117','Europa y Asia Central','Ukraine','State Emergency Service (DSNS)','Nat''l disaster agency','https://dsns.gov.ua','101 / 112 / +38 044 247-31-44','oper@dsns.gov.ua','Civil defence, rescue & emergency response',117,0),
('aid_0118','Europa y Asia Central','Belarus','MChS (Min. for Emergency Situations)','Nat''l disaster agency','https://mchs.gov.by','101 / 112','verify on site','National emergency ministry',118,0),
('aid_0119','Europa y Asia Central','Moldova','IGSU','Nat''l disaster agency','https://igsu.gov.md','112','verify on site','General Inspectorate for Emergency Situations',119,0),
('aid_0120','Europa y Asia Central','Lithuania','Fire & Rescue Dept (PAGD)','Nat''l disaster agency','https://www.vpgt.lt','112','verify on site','Fire & rescue / civil protection',120,0),
('aid_0121','Europa y Asia Central','Latvia','State Fire & Rescue Service (VUGD)','Nat''l disaster agency','https://www.vugd.gov.lv','112','verify on site','State fire & rescue / civil protection',121,0),
('aid_0122','Europa y Asia Central','Estonia','Estonian Rescue Board (Päästeamet)','Nat''l disaster agency','https://www.rescue.ee','112','verify on site','National rescue board & crisis prep',122,0),
('aid_0123','Europa y Asia Central','Russia','EMERCOM (MChS)','Nat''l disaster agency','https://www.mchs.gov.ru','101 / 112','verify on site','Civil defence, emergencies & disaster relief',123,0),
('aid_0124','Europa y Asia Central','Georgia','Emergency Management Service (MIA)','Nat''l disaster agency','https://www.es.gov.ge','112','verify on site','Emergency management service',124,0),
('aid_0125','Europa y Asia Central','Armenia','Ministry of Emergency Situations (MES)','Nat''l disaster agency','http://mes.am','911 / 112 / +374 12 31 77 20','info@mes.am','Civil emergency, rescue & fire',125,0),
('aid_0126','Europa y Asia Central','Azerbaijan','Ministry of Emergency Situations (FHN)','Nat''l disaster agency','https://fhn.gov.az','112','verify on site','National emergency situations ministry',126,0),
('aid_0127','Europa y Asia Central','Kazakhstan','Ministry of Emergency Situations','Nat''l disaster agency','https://www.gov.kz/memleket/entities/emer','112 / 101','verify on site','National emergency situations ministry',127,0),
('aid_0128','Europa y Asia Central','Uzbekistan','Ministry of Emergency Situations','Nat''l disaster agency','https://fvv.uz','112 / 101 / +998 71 234-90-12','info@fvv.uz','National emergency situations ministry',128,0),
('aid_0129','Europa y Asia Central','Turkmenistan','State Service for Civil Defence & Emergencies','Nat''l disaster agency','verify (under Min. Defence)','112','verify on site','Civil defence & emergencies',129,0),
('aid_0130','Europa y Asia Central','Kyrgyzstan','Ministry of Emergency Situations (MChS)','Nat''l disaster agency','https://www.mchs.gov.kg','112 / 161','verify on site','National emergency situations ministry',130,0),
('aid_0131','Europa y Asia Central','Tajikistan','Committee of Emergency Situations & Civil Defence','Nat''l disaster agency','https://khf.tj','112','verify on site','National emergency & civil defence committee',131,0),
('aid_0132','África','African Union','AU Disaster Risk Reduction Unit','Regional body','https://au.int','verify on site','verify on site','Continental DRR coordination',132,0),
('aid_0133','África','West Africa','ECOWAS – Humanitarian & Social Affairs','Regional body','https://www.ecowas.int','verify on site','verify on site','Regional disaster coordination (West Africa)',133,0),
('aid_0134','África','East Africa','IGAD – Disaster Resilience (ICPAC)','Regional body','https://igad.int','verify on site','verify on site','Regional drought/disaster resilience (Horn of Africa)',134,0),
('aid_0135','África','Morocco','Direction de la Protection Civile (Min. Interior)','Nat''l disaster agency','https://www.protectioncivile.gov.ma','15 / 150','verify on site','Civil protection (2023 Al Haouz quake response)',135,0),
('aid_0136','África','Algeria','Direction Générale de la Protection Civile','Nat''l disaster agency','https://www.protectioncivile.dz','14 / 1021','dgpc_contact@protectioncivile.dz','National civil protection (seismic risk)',136,0),
('aid_0137','África','Tunisia','Office National de la Protection Civile (ONPC)','Nat''l disaster agency','http://www.onpc.nat.tn','+216 71 190 100','verify on site','National civil protection',137,0),
('aid_0138','África','Libya','Libyan Civil Defence / General Authority','Nat''l disaster agency','verify on site','verify on site','verify on site','Civil defence & disaster response',138,0),
('aid_0139','África','Egypt','Civil Protection Authority (Min. Interior)','Nat''l disaster agency','verify on site','180','verify on site','National civil protection & firefighting',139,0),
('aid_0140','África','Sudan','National Civil Defence','Nat''l disaster agency','verify on site','verify on site','verify on site','Civil defence & disaster response',140,0),
('aid_0141','África','Ethiopia','Ethiopian Disaster Risk Mgmt Commission (EDRMC)','Nat''l disaster agency','https://edrmc.gov.et','+251 11 551 6407','verify on site','National disaster-risk management',141,0),
('aid_0142','África','Somalia','Somali Disaster Management Agency (SoDMA)','Nat''l disaster agency','https://sodma.gov.so','+252 618 805 090','communications@sodma.gov.so','National disaster management',142,0),
('aid_0143','África','Kenya','National Disaster Operations Centre (NDOC) / NDMU','Nat''l disaster agency','https://www.ndoc.go.ke','+254 800 721 571','infor@ndoc.go.ke','National disaster operations coordination',143,0),
('aid_0144','África','Uganda','Dept of Disaster Prep (Office of Prime Minister)','Nat''l disaster agency','https://opm.go.ug','verify on site','verify on site','National disaster preparedness',144,0),
('aid_0145','África','Tanzania','Disaster Management Dept (PMO)','Nat''l disaster agency','https://www.pmo.go.tz','verify on site','verify on site','National disaster management',145,0),
('aid_0146','África','Rwanda','MINEMA (Ministry of Emergency Management)','Nat''l disaster agency','https://www.minema.gov.rw','170 (toll-free)','minema@gov.rw','Emergency mgmt & refugee affairs',146,0),
('aid_0147','África','DR Congo','Civil Protection (Min. Interior)','Nat''l disaster agency','verify on site','verify on site','verify on site','Civil protection & disaster response',147,0),
('aid_0148','África','Nigeria','NEMA (Nat''l Emergency Management Agency)','Nat''l disaster agency','https://nema.gov.ng','verify on site','info@nema.gov.ng','National emergency response coordination',148,0),
('aid_0149','África','Ghana','NADMO','Nat''l disaster agency','https://nadmo.gov.gh','+233 302 964 882','verify on site','National disaster management',149,0),
('aid_0150','África','Côte d''Ivoire','ONPC (Office Nat''l Protection Civile)','Nat''l disaster agency','https://onpc-ci.org','+225 27 22 47 87 30','protectioncivile@onpc-ci.org','National civil protection',150,0),
('aid_0151','África','Senegal','Direction de la Protection Civile','Nat''l disaster agency','https://interieur.gouv.sn','verify on site','verify on site','National civil protection',151,0),
('aid_0152','África','Mali','Direction Générale Protection Civile','Nat''l disaster agency','verify on site','verify on site','verify on site','National civil protection',152,0),
('aid_0153','África','Burkina Faso','CONASUR','Nat''l disaster agency','https://conasur.gov.bf','+226 25 33 04 07','spconasur@gmail.com','National emergency & rehabilitation council',153,0),
('aid_0154','África','Niger','Dispositif National Prévention/Gestion Catastrophes','Nat''l disaster agency','verify on site','verify on site','verify on site','National disaster prevention/management',154,0),
('aid_0155','África','Chad','Civil Protection (Min. Interior)','Nat''l disaster agency','verify on site','verify on site','verify on site','Civil protection & disaster response',155,0),
('aid_0156','África','Cameroon','Direction de la Protection Civile','Nat''l disaster agency','https://minat.gov.cm','+237 222 234 546','contact@minat.gov.cm','National civil protection',156,0),
('aid_0157','África','South Africa','National Disaster Management Centre (NDMC)','Nat''l disaster agency','https://www.ndmc.gov.za','+27 12 065 0969','enquiries@ndmc.gov.za','National disaster management coordination',157,0),
('aid_0158','África','Zimbabwe','Dept of Civil Protection','Nat''l disaster agency','https://www.civilprotection.org.zw','verify on site','verify on site','National civil protection',158,0),
('aid_0159','África','Zambia','Disaster Management & Mitigation Unit (DMMU)','Nat''l disaster agency','https://dmmu-ovp.gov.zm','+260 211 252692','info@dmmu.gov.zm','National disaster management',159,0),
('aid_0160','África','Malawi','DoDMA (Dept of Disaster Mgmt Affairs)','Nat''l disaster agency','https://www.dodma.gov.mw','verify on site','verify on site','National disaster management',160,0),
('aid_0161','África','Mozambique','INGD','Nat''l disaster agency','https://ingd.gov.mz','verify on site','verify on site','Disaster risk management & reduction',161,0),
('aid_0162','África','Angola','Serviço de Protecção Civil e Bombeiros','Nat''l disaster agency','https://spcb.gov.ao','verify on site','spcb@bombeirodeangola.gov.ao','Civil protection & firefighting',162,0),
('aid_0163','África','Namibia','Directorate Disaster Risk Mgmt (Office of PM)','Nat''l disaster agency','https://opm.gov.na/ddrm','verify on site','verify on site','National disaster-risk management',163,0),
('aid_0164','África','Botswana','National Disaster Management Office (NDMO)','Nat''l disaster agency','verify on site','verify on site','verify on site','National disaster coordination',164,0),
('aid_0165','África','Madagascar','BNGRC','Nat''l disaster agency','https://bngrc.gov.mg','+261 34 05 480 68','verify on site','National disaster-risk mgmt office',165,0),
('aid_0166','África','Mauritius','National Disaster Risk Reduction & Mgmt Centre','Nat''l disaster agency','https://ndrrmc.govmu.org','+230 207 3900','disaster@govmu.org','National DRR & management',166,0),
('aid_0167','Medio Oriente y Asia del Sur','Turkey','AFAD (Disaster & Emergency Mgmt Presidency)','Nat''l disaster agency','https://en.afad.gov.tr','+90 312 258 23 23','verify on site','Lead earthquake & disaster response (2023 quake)',167,0),
('aid_0168','Medio Oriente y Asia del Sur','Syria','Syria Civil Defence (White Helmets)','Volunteer rescue NGO','https://whitehelmets.org','verify on site','verify on site','Search & rescue NW Syria (war + 2023 quake)',168,0),
('aid_0169','Medio Oriente y Asia del Sur','Lebanon','Lebanese Civil Defence','Nat''l disaster agency','http://www.civildefense.gov.lb','125','verify on site','Civil defence, rescue & firefighting',169,0),
('aid_0170','Medio Oriente y Asia del Sur','Israel','National Emergency Mgmt Authority (NEMA/RACHEL) + Home Front Command','Nat''l disaster agency','https://www.mod.gov.il/en/departments/national-emergency-management-authority-nema','104 (Home Front)','verify on site','National emergency management',170,0),
('aid_0171','Medio Oriente y Asia del Sur','Palestine','Palestinian Civil Defense','Nat''l disaster agency','https://pcd.ps','+970 2 295 0130','pr@pcd.ps','Civil defence & rescue',171,0),
('aid_0172','Medio Oriente y Asia del Sur','Jordan','Civil Defence Directorate','Nat''l disaster agency','https://psd.gov.jo/en-us/civil-defense/','+962 6 566 1111','Internet@cdd.gov.jo','Civil defence, rescue & ambulance',172,0),
('aid_0173','Medio Oriente y Asia del Sur','Iraq','Civil Defence Directorate','Nat''l disaster agency','https://moi.gov.iq','115','verify on site','Civil defence & disaster response',173,0),
('aid_0174','Medio Oriente y Asia del Sur','Iran','National Disaster Mgmt Org (NDMO) + Red Crescent','Nat''l disaster agency','https://en.rcs.ir','112 / 125','verify on site','National disaster mgmt (very high seismic risk)',174,0),
('aid_0175','Medio Oriente y Asia del Sur','Saudi Arabia','General Directorate of Civil Defense','Nat''l disaster agency','https://www.998.gov.sa','+966 11 492 5033','998@998.gov.sa','National civil defence & disaster response',175,0),
('aid_0176','Medio Oriente y Asia del Sur','Yemen','Civil Defence (Min. Interior)','Nat''l disaster agency','verify on site','verify on site','verify on site','Civil defence & disaster response',176,0),
('aid_0177','Medio Oriente y Asia del Sur','Oman','Civil Defence & Ambulance Authority (CDAA)','Nat''l disaster agency','https://cdaa.gov.om','9999','info@cdaa.gov.om','Civil defence, rescue & ambulance',177,0),
('aid_0178','Medio Oriente y Asia del Sur','UAE','NCEMA (Nat''l Emergency Crisis & Disasters Mgmt Authority)','Nat''l disaster agency','https://www.ncema.gov.ae','+971 2 4177000','info@ncema.gov.ae','National emergency, crisis & disaster mgmt',178,0),
('aid_0179','Medio Oriente y Asia del Sur','Qatar','Civil Defence (Min. Interior)','Nat''l disaster agency','https://portal.moi.gov.qa','+974 44327734','civildefence@moi.gov.qa','Civil defence & disaster response',179,0),
('aid_0180','Medio Oriente y Asia del Sur','Bahrain','Civil Defence (Min. Interior)','Nat''l disaster agency','https://www.interior.gov.bh','999','verify on site','Civil defence & disaster response',180,0),
('aid_0181','Medio Oriente y Asia del Sur','Kuwait','Kuwait Fire Force / Civil Defence','Nat''l disaster agency','https://www.kfsd.gov.kw','112','verify on site','Firefighting & civil defence',181,0),
('aid_0182','Medio Oriente y Asia del Sur','India','NDMA + NDRF','Nat''l disaster agency','https://ndma.gov.in','+91 11 26701700','controlroom@ndma.gov.in','National disaster mgmt; NDRF = response force',182,0),
('aid_0183','Medio Oriente y Asia del Sur','India','National Center for Seismology (NCS)','Seismic agency','https://seismo.gov.in','+91 11 24344484','verify on site','National earthquake monitoring',183,0),
('aid_0184','Medio Oriente y Asia del Sur','Pakistan','NDMA','Nat''l disaster agency','https://www.ndma.gov.pk','051-111-157-157','info@ndma.gov.pk','National disaster mgmt coordination',184,0),
('aid_0185','Medio Oriente y Asia del Sur','Afghanistan','ANDMA (Afghanistan Nat''l Disaster Mgmt Authority)','Nat''l disaster agency','https://andma.gov.af','+93 20 2527375','info@andma.gov.af','National disaster mgmt (very high quake risk)',185,0),
('aid_0186','Medio Oriente y Asia del Sur','Nepal','NDRRMA','Nat''l disaster agency','https://ndrrma.gov.np','+977 1 5358240','verify on site','Disaster risk reduction & mgmt (2015 Gorkha quake)',186,0),
('aid_0187','Medio Oriente y Asia del Sur','Bangladesh','Dept of Disaster Management (DDM)','Nat''l disaster agency','https://ddm.gov.bd','+880 2 5881549','dg@ddm.gov.bd','National disaster management',187,0),
('aid_0188','Medio Oriente y Asia del Sur','Sri Lanka','Disaster Management Centre (DMC)','Nat''l disaster agency','https://www.dmc.gov.lk','+94 112 136136','info@dmc.gov.lk','National disaster management',188,0),
('aid_0189','Medio Oriente y Asia del Sur','Bhutan','Dept of Disaster Management','Nat''l disaster agency','https://www.ddm.gov.bt','verify on site','verify on site','National disaster management',189,0),
('aid_0190','Medio Oriente y Asia del Sur','Maldives','NDMA','Nat''l disaster agency','https://www.ndma.gov.mv','+960 3333456','info@ndma.gov.mv','National disaster management',190,0),
('aid_0191','Asia Oriental y Pacífico','Japan','Cabinet Office Disaster Mgmt + JMA','Nat''l disaster agency','https://www.bousai.go.jp','+81 3 5253 2111','verify on site','Disaster mgmt; JMA = quake/tsunami warnings',191,0),
('aid_0192','Asia Oriental y Pacífico','Japan','Japan Meteorological Agency (JMA)','Seismic agency','https://www.jma.go.jp','+81 3 6758 3900','verify on site','Earthquake & tsunami early warning',192,0),
('aid_0193','Asia Oriental y Pacífico','China','Ministry of Emergency Management (MEM)','Nat''l disaster agency','https://www.mem.gov.cn','12350','verify on site','National emergency & disaster mgmt',193,0),
('aid_0194','Asia Oriental y Pacífico','South Korea','Ministry of Interior & Safety / NDMI','Nat''l disaster agency','https://www.mois.go.kr','+82 2 2100 3399','moisic@korea.kr','National disaster & safety mgmt',194,0),
('aid_0195','Asia Oriental y Pacífico','North Korea','State Emergency Disaster Committee','Nat''l disaster agency','verify on site','verify on site','verify on site','National disaster committee',195,0),
('aid_0196','Asia Oriental y Pacífico','Taiwan','Central Emergency Operation Center / CWA','Nat''l disaster agency','https://www.cwa.gov.tw','+886 2 2349 1000','eservice@cwa.gov.tw','Disaster ops; CWA = quake/weather warnings',196,0),
('aid_0197','Asia Oriental y Pacífico','Mongolia','NEMA (National Emergency Mgmt Agency)','Nat''l disaster agency','http://en.nema.gov.mn','+976 51 263581','info@nema.gov.mn','National emergency management',197,0),
('aid_0198','Asia Oriental y Pacífico','Indonesia','BNPB','Nat''l disaster agency','https://bnpb.go.id','+62 21 21281200','contact@bnpb.go.id','National disaster mgmt (very high quake risk)',198,0),
('aid_0199','Asia Oriental y Pacífico','Indonesia','BMKG','Seismic agency','https://www.bmkg.go.id','196','cc196@bmkg.go.id','Earthquake, tsunami & weather warnings',199,0),
('aid_0200','Asia Oriental y Pacífico','Philippines','NDRRMC','Nat''l disaster agency','https://ndrrmc.gov.ph','+63 2 8911 5061','verify on site','National disaster risk reduction & mgmt',200,0),
('aid_0201','Asia Oriental y Pacífico','Philippines','PHIVOLCS','Seismic agency','https://www.phivolcs.dost.gov.ph','+63 2 8426 1468','phivolcs_mail@phivolcs.dost.gov.ph','Volcanology & seismology',201,0),
('aid_0202','Asia Oriental y Pacífico','Vietnam','Vietnam Disaster Mgmt Authority (VDMA)','Nat''l disaster agency','https://phongchongthientai.mard.gov.vn','+84 24 37335804','pcttvietnam@mard.gov.vn','National disaster management',202,0),
('aid_0203','Asia Oriental y Pacífico','Thailand','DDPM (Dept of Disaster Prevention & Mitigation)','Nat''l disaster agency','https://www.disaster.go.th','+66 2 637 3000','saraban_center@disaster.go.th','National disaster prevention & mitigation',203,0),
('aid_0204','Asia Oriental y Pacífico','Myanmar','Dept of Disaster Management','Nat''l disaster agency','https://www.dmh.gov.mm','verify on site','verify on site','Disaster mgmt (2025 Mandalay quake)',204,0),
('aid_0205','Asia Oriental y Pacífico','Cambodia','NCDM (Nat''l Committee for Disaster Mgmt)','Nat''l disaster agency','http://www.ncdm.gov.kh','verify on site','administration@ncdm.gov.kh','National disaster management',205,0),
('aid_0206','Asia Oriental y Pacífico','Laos','NDMO / Min. Labour & Social Welfare','Nat''l disaster agency','verify on site','verify on site','verify on site','National disaster management',206,0),
('aid_0207','Asia Oriental y Pacífico','Malaysia','NADMA','Nat''l disaster agency','https://www.nadma.gov.my','+603 8870 4800','admin@nadma.gov.my','National disaster management agency',207,0),
('aid_0208','Asia Oriental y Pacífico','Singapore','SCDF (Singapore Civil Defence Force)','Nat''l disaster agency','https://www.scdf.gov.sg','+65 1800 280 0000','verify on site','Civil defence, fire & rescue',208,0),
('aid_0209','Asia Oriental y Pacífico','Brunei','NDMC (Nat''l Disaster Mgmt Centre)','Nat''l disaster agency','https://www.ndmc.gov.bn','+673 2380266','dcc@ndmc.gov.bn','National disaster management',209,0),
('aid_0210','Asia Oriental y Pacífico','Timor-Leste','Civil Protection Authority','Nat''l disaster agency','verify on site','verify on site','verify on site','National civil protection',210,0),
('aid_0211','Asia Oriental y Pacífico','ASEAN','AHA Centre','Regional body','https://ahacentre.org','+62 21 21012278','info@ahacentre.org','ASEAN disaster mgmt coordination hub',211,0),
('aid_0212','Asia Oriental y Pacífico','Australia','NEMA (National Emergency Mgmt Agency)','Nat''l disaster agency','https://www.nema.gov.au','000','contact@nema.gov.au','National emergency coordination',212,0),
('aid_0213','Asia Oriental y Pacífico','New Zealand','NEMA (Nat''l Emergency Mgmt Agency)','Nat''l disaster agency','https://www.civildefence.govt.nz','+64 4 830 5100','emergency.management@nema.govt.nz','National emergency management',213,0),
('aid_0214','Asia Oriental y Pacífico','New Zealand','GeoNet','Seismic agency','https://www.geonet.org.nz','verify on site','info@geonet.org.nz','Earthquake, tsunami & volcano monitoring',214,0),
('aid_0215','Asia Oriental y Pacífico','Papua New Guinea','National Disaster Centre (NDC)','Nat''l disaster agency','https://pngndc.gov.pg','+675 325 2304','info@pngndc.gov.pg','National disaster coordination',215,0),
('aid_0216','Asia Oriental y Pacífico','Fiji','National Disaster Management Office (NDMO)','Nat''l disaster agency','https://www.ndmo.gov.fj','+679 3319250','neocfiji@gmail.com','National disaster management',216,0),
('aid_0217','Asia Oriental y Pacífico','Vanuatu','NDMO','Nat''l disaster agency','https://www.ndmo.gov.vu','+678 22699','verify on site','National disaster management (high quake/cyclone)',217,0),
('aid_0218','Asia Oriental y Pacífico','Solomon Islands','NDMO','Nat''l disaster agency','https://www.ndmo.gov.sb','verify on site','verify on site','National disaster management',218,0),
('aid_0219','Asia Oriental y Pacífico','Tonga','National Emergency Management Office','Nat''l disaster agency','https://tonganemo.wordpress.com','+676 26340','tonganemo@gmail.com','National disaster mgmt (tsunami/volcano)',219,0),
('aid_0220','Asia Oriental y Pacífico','Samoa','Disaster Management Office (MNRE)','Nat''l disaster agency','https://www.mnre.gov.ws','+685 27307','dmosamoa@gmail.com','National disaster management',220,0),
('aid_0221','Asia Oriental y Pacífico','Pacific','Pacific Community (SPC) / PIEMA','Regional body','https://www.spc.int','+687 26 20 00','spc@spc.int','Pacific regional disaster resilience',221,0);
