// SISMO911 — Telegram bot: shared types + Zod schemas.
// ---------------------------------------------------------------------------
// The bot answers humanitarian case-status queries from VERIFIED database
// records only. Every type here is deliberately small and explicit so the rest
// of the module stays deterministic — no status is ever inferred, guessed, or
// generated by an LLM. The AI layer (src/telegram/intent.ts) may only normalize
// the user's text into one of these structured shapes; the factual answer is
// always built from a DB row.

import { z } from 'zod';

// ---- Public, redaction-safe status vocabulary the bot is allowed to emit ----
// These are the ONLY values that may appear in a Telegram reply. The internal
// D1 vocabularies (persons.status, personas.estado, hospital_patients.estado)
// are mapped onto these in src/adapters/sismo911-api.ts and never leak raw.
export const PUBLIC_STATUSES = [
  'ALIVE',
  'DEATH',
  'MISSING',
  'HOSPITALIZED',
  'LOCATED',
  'SHELTERED',
  'EVACUATED',
  'UNKNOWN',
  'PENDING_VERIFICATION',
] as const;
export type PublicStatus = (typeof PUBLIC_STATUSES)[number];

// A record's verification level. A final life/death/missing status may ONLY be
// shown for VERIFIED or OFFICIAL records; anything else collapses to
// PENDING_VERIFICATION (see computeVerification in the adapter).
export type VerificationLevel = 'OFFICIAL' | 'VERIFIED' | 'PENDING_VERIFICATION';

// Who is asking. Drives redaction + which surfaces may see sensitive detail.
export type ViewerRole = 'public' | 'authorized' | 'admin';

// How strongly the query identified the subject. Strength gates how much we are
// willing to say (see CRITICAL/MATCHING RULES in the README).
export type MatchStrength =
  | 'case_id' // exact case id — strongest
  | 'national_id' // exact cédula — strong
  | 'name_dob' // full name + corroborating DOB/age — strong
  | 'name' // full name only — weak (existence only, no sensitive data)
  | 'partial' // partial name — require more info
  | 'phone'; // phone — sensitive, admin only

// Which underlying registry a record came from.
export type Registry = 'persons' | 'personas' | 'hospital';

// The internal, un-redacted shape the adapter returns. Sensitive fields are
// present here so the audit/redaction layer can deliberately strip them; they
// are NEVER serialized into a public reply.
export interface CaseRecord {
  registry: Registry;
  internalId: string; // raw primary key (persons.id / personas.id / hospital_patients.id)
  caseId: string; // human case id surfaced to users (EXP-/FAM-/HOSP-…)
  fullName: string;
  age: number | null;
  isMinor: boolean;
  protectedFlag: boolean;
  internalStatus: string; // raw status/estado from the row (for audit only)
  publicStatus: PublicStatus; // already verification-gated
  verification: VerificationLevel;
  generalLocation: string | null; // city/state only, street-level dropped
  lastVerifiedMs: number | null;
  matchStrength: MatchStrength;
  // --- sensitive (operator-only); stripped by redactSensitiveFields ----------
  sensitive: {
    cedula?: string | null;
    phone?: string | null;
    address?: string | null;
    hospital?: string | null; // hospital name is a medical detail → not public
    medicalNotes?: string | null;
    familyContact?: string | null;
  };
}

// The deterministic result the response builder renders. A discriminated union
// so buildTelegramResponse can exhaustively switch with no fallthrough.
export type QueryResult =
  | { kind: 'help' }
  | { kind: 'unauthorized' }
  | { kind: 'rate_limited'; retryAfterSec?: number }
  | { kind: 'bad_input'; reason?: string }
  | { kind: 'need_more'; reason: 'partial_name' | 'phone_requires_admin' }
  | { kind: 'no_match' }
  | { kind: 'multiple'; count: number }
  | { kind: 'list'; records: CaseRecord[]; query?: string }
  | { kind: 'match'; record: CaseRecord; detail?: 'full' | 'status' | 'summary' }
  | { kind: 'error' };

// ---- Parsed command shape (command parser → adapter) ------------------------
export type CommandKind =
  | 'buscar'
  | 'caso'
  | 'status'
  | 'hospitalizados'
  | 'missing'
  | 'actualizar'
  | 'muro'
  | 'ayuda'
  | 'unknown';

// Canonical fields/actions the operator write command (/actualizar) can apply.
// 'aprobar' | 'rechazar' are executive-tier (admin) only; the rest are editable
// by any authorized operator.
export type UpdateField = 'estado' | 'ubicacion' | 'contacto' | 'edad' | 'nombre' | 'nota' | 'aprobar' | 'rechazar';

export interface ParsedCommand {
  kind: CommandKind;
  lang: 'es' | 'en';
  cedula?: string;
  name?: string;
  dob?: string; // ISO yyyy-mm-dd if supplied
  caseId?: string;
  phone?: string;
  city?: string;
  // True when the name looks partial (single token / too short) → require more.
  partialName?: boolean;
  // /actualizar: which field/action to apply and its new value (value empty for
  // aprobar/rechazar). caseId carries the target — a case id OR a full name.
  updateField?: UpdateField;
  updateValue?: string;
  // True when parsed from a direct estado shortcut (/fallecido <nombre>…) so the
  // route can downgrade a public sender to a plain search instead of a write.
  statusShortcut?: boolean;
  // /muro: free text to publish on the public wall (empty → show latest posts).
  muroText?: string;
  raw: string;
}

// ---- Telegram webhook payload (only the slice we use, strictly validated) ---
// We accept a permissive superset and pick the fields we need; unknown keys are
// ignored. We never trust the body until it has passed this schema.
export const TgUser = z
  .object({
    id: z.number(),
    is_bot: z.boolean().optional(),
    first_name: z.string().optional(),
    username: z.string().optional(),
    language_code: z.string().optional(),
  })
  .passthrough();

export const TgChat = z
  .object({
    id: z.number(),
    type: z.string().optional(), // 'private' | 'group' | 'supergroup' | 'channel'
  })
  .passthrough();

// Media the intake bot ingests: photos (multiple sizes) and PDF/image documents.
export const TgPhotoSize = z
  .object({ file_id: z.string(), file_unique_id: z.string().optional(), file_size: z.number().optional() })
  .passthrough();
export const TgDocument = z
  .object({ file_id: z.string(), file_name: z.string().optional(), mime_type: z.string().optional(), file_size: z.number().optional() })
  .passthrough();

export const TgMessage = z
  .object({
    message_id: z.number().optional(),
    from: TgUser.optional(),
    chat: TgChat,
    date: z.number().optional(),
    text: z.string().max(4096).optional(),
    caption: z.string().max(4096).optional(),
    photo: z.array(TgPhotoSize).optional(),
    document: TgDocument.optional(),
  })
  .passthrough();

// Bot membership change (added/removed/promoted in a chat or channel).
export const TgChatMemberUpdated = z
  .object({
    chat: TgChat,
    from: TgUser.optional(),
    new_chat_member: z.object({ status: z.string() }).passthrough().optional(),
  })
  .passthrough();

export const TgUpdate = z
  .object({
    update_id: z.number(),
    message: TgMessage.optional(),
    edited_message: TgMessage.optional(),
    // Channel posts arrive as `channel_post` (not `message`), so a channel-feed
    // bot must opt into them via allowed_updates AND read this field.
    channel_post: TgMessage.optional(),
    edited_channel_post: TgMessage.optional(),
    // `my_chat_member` fires when the bot itself is added/removed/promoted — used
    // to auto-subscribe a channel the moment the bot is made an admin there.
    my_chat_member: TgChatMemberUpdated.optional(),
  })
  .passthrough();

export type TelegramUpdate = z.infer<typeof TgUpdate>;
export type TelegramMessage = z.infer<typeof TgMessage>;
