#!/usr/bin/env node
// Generate the STRICT (no 'unsafe-inline') script-src for a Report-Only CSP:
// 'self' + the allowed CDN hosts + a sha256 hash of every STATIC inline <script>
// in public/*.html. Inline event handlers (on*=) and dynamic Worker-rendered
// inline scripts are intentionally NOT covered — they will REPORT under the
// report-only policy, which is exactly how we find what to refactor before
// enforcing. Run: node scripts/gen-csp.mjs  (output is committed into src/lib/csp.ts;
// test/csp-hashes.test.ts fails if the committed hashes drift from the pages).

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';

const CDN_HOSTS = ['https://unpkg.com', 'https://esm.sh', 'https://static.cloudflareinsights.com', 'https://maps.googleapis.com', 'https://js.stripe.com', 'https://*.crossmint.com'];
const CSP_TS = 'src/lib/csp.ts';

export function inlineScriptHashes(dir = 'public') {
  const hashes = new Set();
  for (const f of readdirSync(dir).filter((x) => x.endsWith('.html'))) {
    const html = readFileSync(`${dir}/${f}`, 'utf8');
    for (const m of html.matchAll(/<script(?![^>]*\bsrc=)[^>]*>([\s\S]*?)<\/script>/g)) {
      hashes.add(`'sha256-${createHash('sha256').update(m[1], 'utf8').digest('base64')}'`);
    }
  }
  return [...hashes].sort();
}

export function strictScriptSrc(dir = 'public') {
  return ["'self'", ...CDN_HOSTS, ...inlineScriptHashes(dir)].join(' ');
}

// Render src/lib/csp.ts as a MERGE-FRIENDLY module: one CSP token per line in a
// sorted array joined at runtime. Because each hash is on its own line, two
// branches that each add a different inline-script hash touch DIFFERENT lines, so
// git auto-merges them instead of conflicting on one giant single-line string
// (which is what used to force a manual regen on every rebase).
export function cspModuleSource(dir = 'public') {
  const tokens = ["'self'", ...CDN_HOSTS, ...inlineScriptHashes(dir)];
  const lines = tokens.map((t) => `  ${JSON.stringify(t)},`).join('\n');
  return `// GENERATED by \`node scripts/gen-csp.mjs --write\` — do not hand-edit.
// STRICT (no 'unsafe-inline') script-src for the Report-Only CSP: 'self' + the
// allowed CDN hosts + a sha256 of every STATIC inline <script> in public/*.html.
// One token per line ON PURPOSE so concurrent branches adding different hashes
// auto-merge. Regenerate after editing any inline script:
//   node scripts/gen-csp.mjs --write   (test/csp-hashes.test.ts guards drift)
export const STRICT_SCRIPT_SRC = [
${lines}
].join(' ');
`;
}

// CLI:
//   node scripts/gen-csp.mjs           → print the script-src string (legacy)
//   node scripts/gen-csp.mjs --write   → write the merge-friendly src/lib/csp.ts
if (import.meta.url === `file://${process.argv[1]}`) {
  const hashes = inlineScriptHashes('public');
  process.stderr.write(`# ${hashes.length} inline-script hashes from public/*.html\n`);
  if (process.argv.includes('--write')) {
    writeFileSync(CSP_TS, cspModuleSource('public'));
    process.stderr.write(`# wrote ${CSP_TS} (merge-friendly, ${hashes.length} hashes)\n`);
  } else {
    process.stdout.write(strictScriptSrc('public') + '\n');
  }
}
