// AUTO-GENERATED by build_estados.py / gen_registry.py — do not edit by hand.
// Registry of Venezuela's 25 federal entities for the /estado/:slug seismic maps.
export interface Estado {
  slug: string; name: string; center: [number, number];
  bbox: [number, number, number, number]; // [minlon, minlat, maxlon, maxlat]
  municipios: number; roads: number; places: number;
}

export const ESTADOS: Estado[] = [
  { slug: 'amazonas', name: 'Amazonas', center: [3.4217, -65.6096], bbox: [-67.8643, 0.6474, -63.3549, 6.1959], municipios: 7, roads: 81, places: 43 },
  { slug: 'anzoategui', name: 'Anzoátegui', center: [9.0178, -64.2194], bbox: [-65.751, 7.6616, -62.6878, 10.3741], municipios: 21, roads: 1570, places: 413 },
  { slug: 'apure', name: 'Apure', center: [7.57, -69.3741], bbox: [-72.42, 6.0793, -66.3283, 9.0608], municipios: 8, roads: 284, places: 216 },
  { slug: 'aragua', name: 'Aragua', center: [9.9898, -67.214], bbox: [-67.8816, 9.3837, -66.5464, 10.5959], municipios: 18, roads: 1209, places: 268 },
  { slug: 'barinas', name: 'Barinas', center: [7.57, -69.408], bbox: [-72.4878, 6.0793, -66.3283, 9.0608], municipios: 15, roads: 769, places: 421 },
  { slug: 'bolivar', name: 'Bolívar', center: [6.0346, -63.8419], bbox: [-67.4416, 3.6098, -60.2421, 8.4595], municipios: 11, roads: 2338, places: 345 },
  { slug: 'carabobo', name: 'Carabobo', center: [10.2143, -67.973], bbox: [-68.4287, 9.8115, -67.5173, 10.6171], municipios: 14, roads: 1870, places: 245 },
  { slug: 'cojedes', name: 'Cojedes', center: [9.3095, -68.37], bbox: [-68.988, 8.5333, -67.7519, 10.0856], municipios: 9, roads: 343, places: 211 },
  { slug: 'delta-amacuro', name: 'Delta Amacuro', center: [9.0352, -61.912], bbox: [-64.0185, 7.7652, -59.8055, 10.3053], municipios: 5, roads: 93, places: 65 },
  { slug: 'dependencias-federales', name: 'Dependencias Federales', center: [13.161, -66.3972], bbox: [-70.9916, 10.577, -61.8028, 15.745], municipios: 5, roads: 0, places: 2 },
  { slug: 'distrito-capital', name: 'Distrito Capital', center: [10.475, -67.0123], bbox: [-67.1632, 10.3824, -66.8613, 10.5677], municipios: 1, roads: 2346, places: 5 },
  { slug: 'falcon', name: 'Falcón', center: [11.2742, -69.7093], bbox: [-71.2813, 10.2929, -68.1374, 12.2555], municipios: 25, roads: 687, places: 547 },
  { slug: 'guarico', name: 'Guárico', center: [8.8349, -66.4026], bbox: [-68.0321, 7.6285, -64.7732, 10.0412], municipios: 15, roads: 604, places: 375 },
  { slug: 'la-guaira', name: 'La Guaira', center: [10.5392, -66.8594], bbox: [-67.4123, 10.388, -66.3065, 10.6904], municipios: 1, roads: 454, places: 91 },
  { slug: 'lara', name: 'Lara', center: [10.0714, -69.879], bbox: [-70.8828, 9.3889, -68.8751, 10.7539], municipios: 9, roads: 1249, places: 581 },
  { slug: 'miranda', name: 'Miranda', center: [10.4068, -66.3204], bbox: [-67.22, 9.9372, -65.4209, 10.8764], municipios: 21, roads: 3791, places: 620 },
  { slug: 'monagas', name: 'Monagas', center: [9.3434, -63.0064], bbox: [-64.0185, 8.3816, -61.9943, 10.3053], municipios: 13, roads: 922, places: 304 },
  { slug: 'merida', name: 'Mérida', center: [8.4911, -71.2286], bbox: [-71.9136, 7.6661, -70.5436, 9.316], municipios: 23, roads: 738, places: 228 },
  { slug: 'nueva-esparta', name: 'Nueva Esparta', center: [10.9644, -64.0928], bbox: [-64.468, 10.6903, -63.7177, 11.2386], municipios: 11, roads: 591, places: 110 },
  { slug: 'portuguesa', name: 'Portuguesa', center: [8.9675, -69.3456], bbox: [-70.1873, 8.0915, -68.5039, 9.8435], municipios: 14, roads: 1486, places: 803 },
  { slug: 'sucre', name: 'Sucre', center: [10.429, -63.1775], bbox: [-64.5652, 10.0337, -61.7897, 10.8243], municipios: 15, roads: 845, places: 580 },
  { slug: 'trujillo', name: 'Trujillo', center: [9.4958, -70.7261], bbox: [-71.4567, 8.9519, -69.9955, 10.0397], municipios: 20, roads: 629, places: 199 },
  { slug: 'tachira', name: 'Táchira', center: [8.022, -71.9016], bbox: [-72.4878, 7.3613, -71.3153, 8.6827], municipios: 29, roads: 1732, places: 644 },
  { slug: 'yaracuy', name: 'Yaracuy', center: [10.3041, -68.7339], bbox: [-69.2226, 9.8342, -68.2452, 10.7739], municipios: 14, roads: 829, places: 343 },
  { slug: 'zulia', name: 'Zulia', center: [10.107, -72.0103], bbox: [-73.353, 8.3635, -70.6676, 11.8506], municipios: 21, roads: 1835, places: 268 },
];
